### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by rbmcgowan** [chartello/chartello#7] opened 2023-03-06 02:05 UTC
When adding a new panel I get a nginx web server error  `[error] *235 access forbidden by rule  ...   request: "PUT /chartello/panels/4 HTTP/1.1"`

The issue may be that the post url isn't prefixed with the APP_URL ?  rather it's just `/chartello...` and since the web server has virtual hosts configured it's unable to proceed.

**Comment by matt-daneshvar** [comment] 2023-03-07 01:48
Hey @rbmcgowan, thanks for reporting this. The root cause you've identified sounds right to me, I'll create a PR soon to address it.

**Comment by matt-daneshvar** [comment] 2023-03-07 02:20
@rbmcgowan I just tagged version `0.3.3` with a fix for this. After upgrading, please re-publish Chartello assets to have their latest version in your app: 
```
php artisan vendor:publish --tag=chartello-assets --force
```

Please feel free to re-open the issue if the new version doesn't resolve it for you.

**Comment by rbmcgowan** [comment] 2023-03-07 02:33
appreciated thanks, and thanks for sharing Chartello!

**Comment by rbmcgowan** [comment] 2023-03-07 02:48
Not sure if Im doing something wrong but I still get a ngnix error:
2023/03/07 12:45:33 [error] 856#856: *657 access forbidden by rule, client: 10.211.55.2,  ... request: "PUT /chartello/panels/1 HTTP/1.1",

**Comment by matt-daneshvar** [comment] 2023-03-07 13:50
I'm curious how your `APP_URL` looks like (please feel free to mask the domain if needed). Does it follow any of these patterns?

- example.com/chartello
- example.com/subdirectory/chartello
- subdomain.example.com/chartello
- another pattern?

Does your Laravel app have other `PUT` routes that work correctly?

--- 

This is how the request looks like when I create a panel on my local environment:

<img width="749" alt="image" src="https://user-images.githubusercontent.com/10030505/223440993-c11b4727-58a5-43a4-9d42-a1836b3c10ee.png">

**Comment by rbmcgowan** [comment] 2023-03-07 23:43
Morning, the APP_URL in env is:
APP_URL=https://xxxxx-development.yyyy.com.au

Typical POST routes are like this:
Route::post('/territories', 'territoriesController@store');
Route::post('/territories/search', 'territoriesController@index'); 
Route::patch('/territories/{id}', 'territoriesController@update');
Route::delete('/territories/{id}', 'territoriesController@destroy');

**Comment by rbmcgowan** [comment] 2023-03-07 23:56
are there any logs or other details I could get to help ?

**Comment by matt-daneshvar** [comment] 2023-03-08 01:56
Thanks for sharing the additional context. I tried a few different configurations with subdomains, but I don't seem to be able to replicate. 

> access forbidden by rule, client: 10.211.55.2, ... request: "PUT /chartello/panels/1 HTTP/1.1". 

The more I look at the error you shared, the more I think it must be environment-related. Is there a chance your nginx is configured to deny `PUT` requests?

Did you have any luck setting up Chartello locally?

**Comment by rbmcgowan** [comment] 2023-03-08 03:41
Interesting, never considered that, the Nginx site configuration file has the following:
```
    listen 443;
    location / {
        try_files $uri $uri/ /index.php?$query_string;
		limit_except GET POST { deny all; }
    }
```
so I guess PUT is denied. My routes are all GET/POST/PATCH so I guess PATCH is actually a POST where as I've assumed it was a PUT.  I will need to make the change and test and get back to you.

**Comment by rbmcgowan** [comment] 2023-03-08 06:31
that seems to have fixed it.

**Comment by rbmcgowan** [comment] 2023-03-08 06:44
do you have any notes on how to include a panel within a blade ?

**Comment by matt-daneshvar** [comment] 2023-03-08 13:05
Glad you made it work. 

> do you have any notes on how to include a panel within a blade ?

I don't think that'd be quite straightfoward to do, and even if we managed to make it work, the chances of it breaking in future releases is high, because this package wasn't designed for that. 

I'm curious about your use case, can you share more about what you're trying to achieve?

**Comment by rbmcgowan** [comment] 2023-03-08 23:37
Typical examples I was thinking of were to include/embed a graph of a customers sales revenue on a customer details page, include a few graphs on the users home / landing page showing their progress towards their goals. Basically just small simple graphs that could be included on existing pages to make the pages more interesting & informative at a glance. The graphs could be defined elsewhere, I was hoping a panel could just be added to existing pages.

**Comment by matt-daneshvar** [comment] 2023-03-11 14:35
Thanks for sharing, sounds like a useful feature. I'll keep a note as a possiblity for future versions, but will close this as the original issue has been resolved.

**Closed by matt-daneshvar** 2023-03-11 14:35 UTC
