### ISSUE TITLE
"Class \"Faker\\Factory\" not found",

### ISSUE THREAD

**Issue by gepopp** [chartello/chartello#6] opened 2023-03-05 14:08 UTC
Laravel Version ..................................................... 9.48.0  
  PHP Version .......................................................... 8.1.6  
  Composer Version ..................................................... 2.5.4  
  Environment ..................................................... production  
  Debug Mode ............................................................. OFF  

On production it thows this error:
```
{
    "class": "Error",
    "message": "Class \"Faker\\Factory\" not found",
    "code": 0,
    "file": "/home/ploi/immobilien-redaktion.com/vendor/laravel/framework/src/Illuminate/Database/DatabaseServiceProvider.php:93",
    "trace": [
        "/home/ploi/immobilien-redaktion.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:889",
        "/home/ploi/immobilien-redaktion.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:774",
        "/home/ploi/immobilien-redaktion.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:860",
        "/home/ploi/immobilien-redaktion.com/vendor/laravel/framework/src/Illuminate/Container/Container.php:710",
        "/home/ploi/immobilien-redaktion.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:845",
        "/home/ploi/immobilien-redaktion.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php:842",
        "/home/ploi/immobilien-redaktion.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/Factory.php:153",
        "/home/ploi/immobilien-redaktion.com/vendor/chartello/chartello/src/Models/Dashboard.php:18",
        "/home/ploi/immobilien-redaktion.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factories/HasFactory.php:16",
        "/home/ploi/immobilien-redaktion.com/vendor/chartello/chartello/src/Http/Controllers/HomeController.php:23",
        "/home/ploi/immobilien-redaktion.com/vendor/chartello/chartello/src/Http/Controllers/HomeController.php:15",
        "/home/ploi/immobilien-redaktion.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:46",
        "/home/ploi/immobilien-redaktion.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php:260",
        "/home/ploi/immobilien-redaktion.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php:205",
        "/home/ploi/immobilien-redaktion.com/vendor/laravel/framework/src/Illuminate/Routing/Router
```

**Comment by matt-daneshvar** [comment] 2023-03-05 23:08
Thanks for reporting, @gepopp. I just tagged [v0.3.1](https://github.com/chartello/chartello/releases/tag/v0.3.1), let me know if it fixes it for you.

**Comment by matt-daneshvar** [comment] 2023-03-08 01:57
Closing the issue for now, please feel free to re-open it if the issue isn't resolved for you yet.

**Closed by matt-daneshvar** 2023-03-08 01:57 UTC
